[package]
name = "rcompare"
version = "0.1.1"
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fasthash = "0.4"
clap = { version = "4", features = ["derive"] }
