[package]
name = "rcompare"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "test"
test = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fasthash = "0.4"

[profile.release]
debug = true
